echo "Тестовый запуск обучения"
rem https://docs.ultralytics.com/ru/usage/cfg/#augmentation-settings
set CUDA_VISIBLE_DEVICES=0
rem echo Старт модели n
rem yolo task=detect mode=train model=yolov8n.pt name=wagnumbers_1280_n data=coco8.yaml epochs=300 patience=10000 batch=0.95 imgsz=1280 save=True save_period=100 cache=True device=0 pretrained=True deterministic=False rect=True close_mosaic=100 amp=True label_smoothing=0.5 overlap_mask=True lr0=0.1 lrf=0.001 momentum=0.5 warmup_epochs=30.0 box=10 cls=1 conf=0.05 iou=0.5 max_det=300 augment=False mixup=0 auto_augment='autoaugment' agnostic_nms=True show_labels=False show_conf=False show_boxes=False nms=True hsv_h=0.015 hsv_s=0.7 hsv_v=0.4 degrees=0 translate=0 scale=0 shear=0 perspective=0 flipud=0 fliplr=0 bgr=0 mosaic=0 copy_paste=0.0 erasing=0 crop_fraction=1 dropout=0
rem echo Старт модели s                                                                                                                                       
yolo task=detect mode=train model=yolov8s.pt name=wagnumbers_1280_s data=coco8.yaml epochs=300 patience=10000 batch=0.95 imgsz=1280 save=True save_period=100 cache=True device=0 pretrained=True deterministic=False rect=True close_mosaic=100 amp=True label_smoothing=0.5 overlap_mask=True lr0=0.1 lrf=0.001 momentum=0.5 warmup_epochs=30.0 box=10 cls=1 conf=0.05 iou=0.5 max_det=300 augment=False mixup=0 auto_augment='autoaugment' agnostic_nms=True show_labels=False show_conf=False show_boxes=False nms=True hsv_h=0.015 hsv_s=0.7 hsv_v=0.4 degrees=0 translate=0 scale=0 shear=0 perspective=0 flipud=0 fliplr=0 bgr=0 mosaic=0 copy_paste=0.0 erasing=0 crop_fraction=1 dropout=0
rem echo Старт модели l                                                                                                                                       
rem yolo task=detect mode=train model=yolov10l.pt name=wagnumbers_1280_l data=coco8.yaml epochs=300 patience=10000 batch=0.95 imgsz=1280 save=True save_period=100 cache=True device=0 pretrained=True deterministic=False rect=True close_mosaic=100 amp=True label_smoothing=0.5 overlap_mask=True lr0=0.1 lrf=0.001 momentum=0.5 warmup_epochs=30.0 box=10 cls=1 conf=0.05 iou=0.5 max_det=300 augment=False mixup=0 auto_augment='autoaugment' agnostic_nms=True show_labels=False show_conf=False show_boxes=False nms=True hsv_h=0.015 hsv_s=0.7 hsv_v=0.4 degrees=0 translate=0 scale=0 shear=0 perspective=0 flipud=0 fliplr=0 bgr=0 mosaic=0 copy_paste=0.0 erasing=0 crop_fraction=1 dropout=0
pause